export type TravelPackage = {
  title: string
  duration: string
  tagline: string
  image: string
  highlights: string[]
  itinerary: string[]
}

export const TRAVEL_PACKAGES: TravelPackage[] = [
  {
    title: "Bali",
    duration: "4N/5D",
    tagline: "Beach bliss, cliffside temples, and iconic sunsets.",
    image: "/Bali.jpg",
    highlights: ["Benoa Beach", "Ubud vibes", "Tanah Lot"],
    itinerary: [
      "Day 1: Arrival – Leisure",
      "Day 2: Benoa Beach + Uluwatu Temple",
      "Day 3: Kintamani – Ubud – Bali Swing",
      "Day 4: Bedugul – Handara Gate – Tanah Lot",
      "Day 5: Departure",
    ],
  },
  {
    title: "Dubai",
    duration: "5N/6D",
    tagline: "Skyline luxury, desert thrill, and dazzling nights.",
    image: "/dubai.jpg",
    highlights: ["City Tour", "Desert Safari", "Burj Khalifa"],
    itinerary: [
      "Day 1: Arrival – Hotel transfer – Leisure",
      "Day 2: Dubai City Tour + Dhow Cruise Dinner",
      "Day 3: Desert Safari with BBQ Dinner",
      "Day 4: Burj Khalifa + Dubai Mall & Fountain Show",
      "Day 5: Leisure / Optional Tour",
      "Day 6: Departure",
    ],
  },
  {
    title: "Sri Lanka",
    duration: "5N/6D",
    tagline: "Tea trails, golden beaches, and cultural charm.",
    image: "/Sri Lanka.jpg",
    highlights: ["Kandy", "Tea Gardens", "Bentota"],
    itinerary: [
      "Day 1: Arrival – Colombo to Kandy",
      "Day 2: Kandy City Tour & Cultural Show",
      "Day 3: Kandy to Nuwara Eliya (Tea Gardens)",
      "Day 4: Nuwara Eliya to Bentota",
      "Day 5: Bentota Sightseeing & Leisure",
      "Day 6: Colombo City Tour – Departure",
    ],
  },
  {
    title: "Vietnam",
    duration: "6N/7D",
    tagline: "Cruises, lantern towns, and epic viewpoints.",
    image: "/Vietnam.webp",
    highlights: ["Hanoi", "Halong Bay", "Golden Bridge"],
    itinerary: [
      "Day 1: Arrival Hanoi – Leisure",
      "Day 2: Hanoi City Tour + Water Puppet Show",
      "Day 3: Halong Bay Cruise (Overnight)",
      "Day 4: Return to Hanoi – Fly to Da Nang",
      "Day 5: Ba Na Hills & Golden Bridge",
      "Day 6: Hoi An Ancient Town",
      "Day 7: Departure",
    ],
  },
  {
    title: "Vietnam + Cambodia",
    duration: "6N/7D",
    tagline: "Two countries. One legendary journey.",
    image: "/Vietnam + Cambodia.jpg",
    highlights: ["Halong Cruise", "Siem Reap", "Angkor Wat"],
    itinerary: [
      "Day 1: Arrival Hanoi – Leisure",
      "Day 2: Hanoi City Tour + Water Puppet Show",
      "Day 3: Halong Bay Cruise (Overnight on Cruise)",
      "Day 4: Return to Hanoi – Fly to Siem Reap",
      "Day 5: Angkor Thom & Angkor Wat Tour",
      "Day 6: Siem Reap City / Tonle Sap (Optional)",
      "Day 7: Departure",
    ],
  },
  {
    title: "Thailand",
    duration: "4N/5D",
    tagline: "City lights, island fun, and showtime energy.",
    image: "/Thailand.avif",
    highlights: ["Pattaya", "Coral Island", "Bangkok"],
    itinerary: [
      "Day 1: Arrival at Bangkok Airport – Transfer to Pattaya – Check-in & leisure",
      "Day 2: Coral Island Tour with speedboat – Evening Alcazar/Tiffany Show",
      "Day 3: Transfer Pattaya to Bangkok – Bangkok City Tour (temples & shopping)",
      "Day 4: Safari World & Marine Park / Free day for shopping & leisure",
      "Day 5: Departure from Bangkok Airport",
    ],
  },
  {
    title: "Phuket + Krabi",
    duration: "5N/6D",
    tagline: "Island-hopping and turquoise-water days.",
    image: "/Phuket + Krabi.jpg",
    highlights: ["Phi Phi", "Krabi Islands", "Beach time"],
    itinerary: [
      "Day 1: Arrive Phuket – Hotel check-in & leisure",
      "Day 2: Phi Phi Island tour by speedboat",
      "Day 3: Phuket city tour & free time",
      "Day 4: Transfer Phuket to Krabi – Relax",
      "Day 5: Krabi Four Island tour",
      "Day 6: Check-out & departure",
    ],
  },
  {
    title: "Maldives",
    duration: "4N/5D",
    tagline: "Overwater romance and pure ocean calm.",
    image: "/Maldives.jpeg",
    highlights: ["Beach Villa", "Pool Villa", "Water sports"],
    itinerary: [
      "Day 1: Arrival – Speedboat/Seaplane transfer – Check-in Beach Villa",
      "Day 2: Leisure day at resort – Beach activities (Beach Villa)",
      "Day 3: Upgrade to Pool Villa – Relax & enjoy private pool",
      "Day 4: Leisure day – Water sports / spa (Pool Villa)",
      "Day 5: Check-out – Transfer to airport – Departure",
    ],
  },
  {
    title: "Japan",
    duration: "9N/10D",
    tagline: "Modern wonders, timeless culture, and bucket-list parks.",
    image: "/Japan.jpg",
    highlights: ["Tokyo", "Kyoto", "Mt. Fuji"],
    itinerary: [
      "Day 1: Arrive Tokyo",
      "Day 2: Tokyo City Tour",
      "Day 3: Mt. Fuji & Hakone",
      "Day 4: Leisure / Disneyland",
      "Day 5: Tokyo → Kyoto (Bullet Train)",
      "Day 6: Kyoto Sightseeing",
      "Day 7: Kyoto → Osaka + City Tour",
      "Day 8: Hiroshima Day Trip",
      "Day 9: Leisure / Universal Studios",
      "Day 10: Departure",
    ],
  },
  {
    title: "Nepal",
    duration: "5N/6D",
    tagline: "Himalayan views and soulful adventures.",
    image: "/Nepal.jpg",
    highlights: ["Kathmandu", "Pokhara", "Sunrise"],
    itinerary: [
      "Day 1: Arrival Kathmandu – Leisure",
      "Day 2: Kathmandu sightseeing (Pashupatinath, Boudhanath, Swayambhunath)",
      "Day 3: Transfer to Pokhara – Scenic drive",
      "Day 4: Pokhara sightseeing & Sarangkot sunrise",
      "Day 5: Return to Kathmandu –",
      "Day 6: Departure",
    ],
  },
  {
    title: "Bhutan",
    duration: "5N/6D",
    tagline: "Peaceful valleys and the iconic Tiger's Nest.",
    image: "/Bhutan .jpg",
    highlights: ["Thimphu", "Punakha", "Tiger's Nest"],
    itinerary: [
      "Day 1: Arrival Paro – Transfer to Thimphu | Leisure evening",
      "Day 2: Thimphu sightseeing (Buddha Point, Memorial Chorten, Tashichho Dzong)",
      "Day 3: Transfer to Punakha via Dochula Pass | Punakha Dzong visit",
      "Day 4: Transfer to Paro | Local sightseeing",
      "Day 5: Paro sightseeing – Tiger's Nest Monastery hike",
      "Day 6: Departure from Paro ✈️",
    ],
  },
  {
    title: "Azerbaijan",
    duration: "5N/6D",
    tagline: "City elegance, fire temples, and scenic escapes.",
    image: "/Azerbaijan.jpg",
    highlights: ["Baku", "Gobustan", "Gabala"],
    itinerary: [
      "Day 1: Arrival in Baku, airport transfer, evening at leisure.",
      "Day 2: Baku city tour – Old City, Flame Towers, Baku Boulevard.",
      "Day 3: Absheron tour – Ateshgah Fire Temple & Yanardag.",
      "Day 4: Gabala day trip – Nohur Lake & Tufandag Mountains.",
      "Day 5: Gobustan tour – Rock carvings & Mud Volcanoes, evening shopping.",
      "Day 6: Departure from Baku with wonderful memories.",
    ],
  },
  {
    title: "Azerbaijan + Georgia",
    duration: "7N/8D",
    tagline: "Two cultures, one unforgettable route.",
    image: "/Azerbaijan + Georgia.jpg",
    highlights: ["Baku", "Tbilisi", "Kazbegi"],
    itinerary: [
      "Day 1: Arrive Baku – airport transfer, evening at leisure.",
      "Day 2: Baku City Tour – Old City, Flame Towers, Boulevard.",
      "Day 3: Absheron + Gobustan – Fire Temple, Yanardag, Mud Volcanoes.",
      "Day 4: Fly/Transfer to Tbilisi – evening walk & leisure.",
      "Day 5: Tbilisi City Tour – Old Town, Narikala Fortress, Sulphur Baths area.",
      "Day 6: Kazbegi Day Trip – Ananuri Fortress & Gergeti Trinity Church.",
      "Day 7: Kakheti Wine Region – vineyards & scenic countryside.",
      "Day 8: Departure from Tbilisi.",
    ],
  },
]
